"""Generate every printable STL for the SkyArm.

    python -m skyarm.cad.generate [output_dir]      (default: skyarm/stl)

Each mesh is validated (watertight, positive volume, fits the print bed)
before export, and a MANIFEST.md is written with quantities, materials
and print notes.
"""

from __future__ import annotations

import sys
from pathlib import Path

from .. import spec
from . import cycloidal, parts
from .primitives import check_part

# name -> (builder, qty, material, notes)
def catalogue():
    cat = {}
    for cs in (spec.CYCLO_BIG, spec.CYCLO_MID, spec.CYCLO_YAW, spec.CYCLO_SMALL):
        joint = {v: k for k, v in spec.JOINT_GEARBOX.items()}.get(cs, "")
        boxes = cycloidal.parts(cs)
        for name, mesh in boxes.items():
            qty = 2 if name.endswith("_disc") else 1
            mat = "PETG (0.12 mm layers)" if name.endswith(("_disc", "_cam")) \
                else "PETG-CF, 6 walls, 50% gyroid"
            cat[name] = (mesh, qty, mat, f"{cs.reduction}:1 reducer — {joint}")
    gantry = {
        "ceiling_bracket": (parts.ceiling_bracket, 8, "PETG-CF",
                            "lag-screw to joists every ~45 cm"),
        "x_truck": (parts.x_truck, 2, "PETG-CF", "V wheels on ceiling 2040 rails"),
        "bridge_endcap": (parts.bridge_endcap, 2, "PETG-CF", "2060 beam -> truck"),
        "y_carriage": (parts.y_carriage, 1, "PETG-CF", "carries the whole arm"),
        "gantry_motor_mount": (parts.gantry_motor_mount, 3, "PETG-CF",
                               "2x X drive + 1x Y drive"),
        "belt_tensioner": (parts.belt_tensioner, 3, "PETG", ""),
        "shoulder_clevis": (parts.shoulder_clevis, 2, "PETG-CF",
                            "print 1 + 1 mirrored in slicer"),
        "elbow_clevis": (parts.elbow_clevis, 1, "PETG-CF", ""),
        "forearm_clevis": (parts.forearm_clevis, 1, "PETG-CF", ""),
        "wrist_bracket": (parts.wrist_bracket, 1, "PETG-CF", ""),
        "roll_housing": (parts.roll_housing, 1, "PETG-CF", ""),
        "roll_pulley": (parts.roll_pulley, 1, "PETG, 0.12 mm layers",
                        "or buy aluminium 100T GT2"),
        "gripper_base": (parts.gripper_base, 1, "PETG-CF", ""),
        "gripper_finger": (parts.gripper_finger, 1, "PETG-CF, TPU pads", ""),
        "gripper_finger_mirror": (lambda: parts.gripper_finger(True), 1,
                                  "PETG-CF, TPU pads", ""),
    }
    for name, (fn, qty, mat, note) in gantry.items():
        cat[name] = (fn(), qty, mat, note)
    return cat


def main(out_dir: str | None = None) -> int:
    out = Path(out_dir or Path(__file__).resolve().parent.parent / "stl")
    out.mkdir(parents=True, exist_ok=True)
    rows = []
    total_volume = 0.0
    for name, (mesh, qty, mat, note) in sorted(catalogue().items()):
        check_part(mesh, name, spec.PRINT_VOLUME_MM)
        path = out / f"{name}.stl"
        mesh.export(path)
        vol = mesh.volume / 1000.0
        total_volume += vol * qty
        rows.append((name, qty, vol, mat, note))
        print(f"  {name:28s} x{qty}  {vol:7.1f} cm3  -> {path.name}")

    manifest = out / "MANIFEST.md"
    with open(manifest, "w") as f:
        f.write("# SkyArm printed parts manifest\n\n")
        f.write("Generated by `python -m skyarm.cad.generate` — do not edit.\n\n")
        f.write("| part | qty | volume (cm3) | material | notes |\n")
        f.write("|---|---|---|---|---|\n")
        for name, qty, vol, mat, note in rows:
            f.write(f"| {name}.stl | {qty} | {vol:.1f} | {mat} | {note} |\n")
        density = 1.3 / 1000.0  # PETG-CF kg/cm3
        f.write(f"\nTotal plastic ~= {total_volume:.0f} cm3 "
                f"(~{total_volume * density:.1f} kg at 100% — actual prints "
                f"with infill will use roughly half).\n")
    print(f"\n{len(rows)} part files + {manifest.name} written to {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1] if len(sys.argv) > 1 else None))
